Models/Ticket.cs
using System.ComponentModel.DataAnnotations;

namespace SRC_Travel_Agencies.Models
{
    public class Ticket
    {
        [Key]
        public int TicketId { get; set; }

        // Properties from reserve1
        public int BookingId { get; set; }
        public int BusId { get; set; }

        // Properties from reserve2
        [Required]
        public string From { get; set; }
        [Required]
        public string To { get; set; }
        [Required]
        public DateTime Date { get; set; }
        [Required]
        public string Distance { get; set; }
        [Required]
        public string Estimated_Hours { get; set; }

        // Properties from reserve3
        [Required]
        public string Seat_Number { get; set; }
        [Required]
        public int Ticket_Price { get; set; }

        // Properties from reserve4
        [Required]
        public string Name { get; set; }
        [Required]
        public string Email { get; set; }
        [Required]
        public int Phone { get; set; }
    }
}

Controllers/Ticket_ReservationController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SRC_Travel_Agencies.Context;
using SRC_Travel_Agencies.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography;

namespace SRC_Travel_Agencies.Controllers
{
    public class Ticket_ReservationController : Controller
    {
        private readonly SqlContext sc;

        public Ticket_ReservationController(SqlContext context)
        {
            sc = context;
        }
        public IActionResult Index()
        {
            var buses = sc.uploads.Include(x => x.Category).ToList();

            var em = HttpContext.Session.GetString("Employee");
            if (em != null)
            {
                ViewBag.login = em;
                ViewBag.ActiveStep = "AvailableBuses";
                ViewBag.BusId = HttpContext.Session.GetInt32("BusId");
                return View(buses);
            }
            else
            {
                return RedirectToAction("login", "Admin");
            }
        }

        [HttpPost]
        public IActionResult Index(int id)
        {
            var reservation = new reserve1
            {
                BusId = id
            };

            sc.Reserves.Add(reservation);
            sc.SaveChanges();

            ViewBag.ActiveStep = "TravelDates";

            return RedirectToAction("Travel_Dates");
        }

        public IActionResult Travel_Dates()
        {
            var em = HttpContext.Session.GetString("Employee");
            if (em != null)
            {
                ViewBag.login = em;
                ViewBag.ActiveStep = "TravelDates";
                return View();
            }
            else
            {
                return RedirectToAction("login", "Admin");
            }
        }

        [HttpPost]
        public IActionResult Travel_Dates(reserve2 rs2)
        {
            if (rs2 == null || string.IsNullOrEmpty(rs2.From) || string.IsNullOrEmpty(rs2.TO) || string.IsNullOrEmpty(rs2.Distance) || string.IsNullOrEmpty(rs2.Estimated_Hours))
            {
                ModelState.AddModelError(string.Empty, "");
                return View(rs2);
            }
            sc.Reserves2.Add(rs2);
            sc.SaveChanges();
            ModelState.Clear();

            ViewBag.ActiveStep = "BookSeat";

            return RedirectToAction("Book_Seats");
        }

        public IActionResult Book_Seats()
        {
            var buses = sc.Reserves.ToList(); // BusID
            var dates = sc.Reserves2.ToList(); // Date
            var tickets = sc.Ticket.ToList(); // tickets.BusId == bus.BusId && tickets.Date == date.Date

            // Filter tickets based on conditions
            var filteredTickets = tickets.Where(t => buses.Any(b => b.BusId == t.BusId) && dates.Any(d => d.Date == t.Date)).ToList();

            var em = HttpContext.Session.GetString("Employee");
            if (em != null)
            {
                ViewBag.login = em;
                ViewBag.SeatNumbers = filteredTickets.Select(t => t.Seat_Number).ToList();
                ViewBag.ActiveStep = "BookSeat";
                return View();
            }
            else
            {
                return RedirectToAction("login", "Admin");
            }
        }


        [HttpPost]
        public IActionResult Book_Seats(reserve3 model)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
           
            string selectedSeatNumbers = model.Seat_Number;
            
            int price = model.Ticket_Price;
            var reservation = new reserve3
            {
                Seat_Number = selectedSeatNumbers,
                Ticket_Price = price
            };
            if (ModelState.IsValid)
            {
                sc.Reserves3.Add(reservation);
                sc.SaveChanges();
                ViewBag.ActiveStep = "Customer";
                return RedirectToAction("Customer");
            }
            else
            {
                return View();
            }
            
        }

        public IActionResult Customer()
        {
            var em = HttpContext.Session.GetString("Employee");
            if (em != null)
            {
                ViewBag.login = em;
                ViewBag.ActiveStep = "Customer";
                return View();
            }
            else
            {
                return RedirectToAction("login", "Admin");
            }
        }

        [HttpPost]
        public IActionResult Customer(reserve4 rs4)
        {
            if (rs4 == null)
            {
                ModelState.AddModelError("", "Invalid bus data");
                return View();
            }
            sc.Reserves4.Add(rs4);
            sc.SaveChanges();
            ModelState.Clear();

            ViewBag.ActiveStep = "Appreciation";

            return RedirectToAction("Appreciation");
        }

        public IActionResult Appreciation()
        {
            var em = HttpContext.Session.GetString("Employee");
            if (em != null)
            {
                ViewBag.login = em;
                ViewBag.ActiveStep = "Appreciation";
                return View();
            }
            else
            {
                return RedirectToAction("login", "Admin");
            }
        }

        public IActionResult GenerateTicket()
        {
            var reserve1Data = sc.Reserves.FirstOrDefault();
            var reserve2Data = sc.Reserves2.FirstOrDefault();
            var reserve3Data = sc.Reserves3.FirstOrDefault();
            var reserve4Data = sc.Reserves4.FirstOrDefault();

            if (reserve1Data != null && reserve2Data != null && reserve3Data != null && reserve4Data != null)
            {
                var ticket = new Ticket
                {
                    BookingId = reserve1Data.BookingId,
                    BusId = reserve1Data.BusId,
                    From = reserve2Data.From,
                    To = reserve2Data.TO,
                    Date = reserve2Data.Date,
                    Distance = reserve2Data.Distance,
                    Estimated_Hours = reserve2Data.Estimated_Hours,
                    Seat_Number = reserve3Data.Seat_Number,
                    Ticket_Price = reserve3Data.Ticket_Price,
                    Name = reserve4Data.Name,
                    Email = reserve4Data.Email,
                    Phone = reserve4Data.phone
                };

                sc.Ticket.Add(ticket);
                sc.SaveChanges();

                sc.Reserves.Remove(reserve1Data);
                sc.Reserves2.Remove(reserve2Data);
                sc.Reserves3.Remove(reserve3Data);
                sc.Reserves4.Remove(reserve4Data);
                sc.SaveChanges();

                return RedirectToAction("Ticket");
            }
            return RedirectToAction("Appreciation");
        }

        public IActionResult Ticket()
        {
            var lastTicket = sc.Ticket.OrderByDescending(e => e.TicketId).FirstOrDefault();
            List<Ticket> ticketList = new List<Ticket>();
            if (lastTicket != null)
            {
                ticketList.Add(lastTicket);
            }

            var em = HttpContext.Session.GetString("Employee");
            if (em != null)
            {
                ViewBag.login = em;
                ViewBag.ActiveStep = "Ticket";
                return View(ticketList);
            }
            else
            {
                return RedirectToAction("login", "Admin");
            }
        }

        public IActionResult UpdatePass()
        {
            var em = HttpContext.Session.GetString("Employee");
            if (em != null)
            {
                ViewBag.login = em;
                return View();
            }
            else
            {
                return RedirectToAction("login", "Admin");
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> UpdatePass(string password)
        {
            var em = HttpContext.Session.GetString("Employee");
            if (em != null)
            {
                var employee = await sc.Employees.FirstOrDefaultAsync(e => e.Username == em);
                if (employee != null)
                {
                    employee.Password = password;
                    await sc.SaveChangesAsync();
                    return RedirectToAction("Index"); // Redirect to appropriate action after password update
                }
            }
            return RedirectToAction("login", "Admin"); // Redirect to login if employee not found or not logged in
        }

        public IActionResult Login()
        {
            var em = HttpContext.Session.GetString("Employee");
            if (em != null)
            {
                ViewBag.login = em;
                return View();
            }
            else
            {
                return RedirectToAction("login", "Admin");
            }
        }

        public void CleanupOldTickets()
        {
            var oneWeekAgo = DateTime.Now.AddDays(-7);
            var oldTickets = sc.Ticket.Where(t => t.Date < oneWeekAgo).ToList();

            sc.Ticket.RemoveRange(oldTickets);
            sc.SaveChanges();
        }

        public IActionResult Booking_Details()
        {
            var ticket = sc.Ticket.ToList();
            var em = HttpContext.Session.GetString("Employee");
            if (em != null)
            {
                ViewBag.login = em;
                return View(ticket);
            }
            else
            {
                return RedirectToAction("login", "Admin");
            }
        }

        public IActionResult Cancel_Ticket(int id)
        {
            var ticket = sc.Ticket.Find(id);
            if (ticket == null)
            {
                return RedirectToAction("error404");
            }

Views/Ticket_Reservation/Appreciation.cshtml
@model SRC_Travel_Agencies.Models.Ticket

@{
    ViewData["Title"] = "Appreciation";
    Layout = "~/Views/Shared/header_footer.cshtml";
}
<i class="fa fa-check-circle" style="font-size:100px;color:green"></i>
<h3>Ticket Booked</h3>

<p>Dear @ViewBag.login,</p>
    <p>Thank you for your outstanding contributions!</p>
<hr />
<div class="row">
    <div class="col-md-4">
       <form asp-action="GenerateTicket">
           <button type="submit" class="btn btn-success">Generate your Ticket</button>
        </form>
    </div>
</div>

<div>
</div>

Views/Ticket_Reservation/Booking_Details.cshtml
@model IEnumerable<SRC_Travel_Agencies.Models.Ticket>

@{
    ViewData["Title"] = "Booking_Details";
    Layout = "~/Views/Shared/header_no_nav.cshtml";
}

 <div class="table-responsive">
<table class="table">
    <thead>
        <tr>
            <th>
                    @Html.DisplayNameFor(model => model.TicketId)
            </th>
            <th>
                    @Html.DisplayNameFor(model => model.BusId)
            </th>
            <th>
                    @Html.DisplayNameFor(model => model.From)
            </th>
            <th>
                    @Html.DisplayNameFor(model => model.To)
            </th>
            <th>
                    @Html.DisplayNameFor(model => model.Date)
            </th>
            <th>
                    @Html.DisplayNameFor(model => model.Distance)
            </th>
            <th>
                    Estimated Hours
            </th>
            <th>
                    Seat No.
            </th>
            <th>
                    Ticket Price
            </th>
            <th>
                    @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                    @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                    @Html.DisplayNameFor(model => model.Phone)
            </th>
            <th>
                   Cancle Ticket
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
            @foreach (var item in Model)
            {
            <tr>
                <td>
                        @Html.DisplayFor(modelItem => item.TicketId)
                </td>
                <td>
                        @Html.DisplayFor(modelItem => item.BusId)
                </td>
                <td>
                        @Html.DisplayFor(modelItem => item.From)
                </td>
                <td>
                        @Html.DisplayFor(modelItem => item.To)
                </td>
                <td>
                        @Html.DisplayFor(modelItem => item.Date)
                </td>
                <td>
                        @Html.DisplayFor(modelItem => item.Distance)
                </td>
                <td>
                        @Html.DisplayFor(modelItem => item.Estimated_Hours)
                </td>
                <td>
                        @Html.DisplayFor(modelItem => item.Seat_Number)
                </td>
                <td>
                        @Html.DisplayFor(modelItem => item.Ticket_Price)
                </td>
                <td>
                        @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                        @Html.DisplayFor(modelItem => item.Email)
                </td>
                <td>
                        @Html.DisplayFor(modelItem => item.Phone)
                </td>
                <td>
                        <a asp-action="Cancel_Ticket" asp-route-id="@item.TicketId" class="btn btn-success">Cancle Ticket</a>
                </td>
            </tr>
            }
    </tbody>
</table>
 </div>
 <div class="row justify-content-center buttons">
            <a href="@Url.Action("Index", "Ticket_Reservation")" class="btn btn-success">Continue Booking</a>
        </div>

                        <script>
    window.onload = function () {
        var table = document.getElementById('ticketTable');
        if (table.rows.length > 10) {
            table.classList.add('scrollable');
        }
    };
</script>

<style>
    /* Style for scrollbar */
    .scrollable {
        max-height: 300px; /* Adjust height as needed */
        overflow-y: auto;
    }
</style>

Views/Ticket_Reservation/Customer.cshtml
@model SRC_Travel_Agencies.Models.reserve4
@{
    ViewData["Title"] = "Customer";
    Layout = "~/Views/Shared/header_footer.cshtml";
}


<!-- PERSONAL INFO -->
<fieldset class="animated fadeIn p-info">
    
                <form asp-action="Customer">
    <div class="form-row">
        <div class="form-group col-md-6">
            <label for="name">Full Name</label>
            <input type="text" class="form-control"  asp-for="Name" name="name" placeholder="Elisha" onkeyup="verifyInfoForm()" id="name" required>
        </div>
        <div class="form-group col-md-6">
            <label for="phone">Mobile No.</label>
            <input asp-for="phone" class="form-control" required placeholder="+92312345689" />
            <span asp-validation-for="phone" class="text-danger"></span>
        </div>
    </div>
    <div class="form-row">
        
        <div class="form-group col-md-6">
            <label for="email">Email</label>
            <input type="text" class="form-control"  asp-for="Email"  id="email" name="email" placeholder="elisha@gamil.com" onkeyup="verifyInfoForm()" required>
        </div>
    </div>
    <div class="row justify-content-center buttons">
        <a href="@Url.Action("Book_Seats", "Ticket_Reservation")" class="btn btn-success book_btn" data-bus="1">Back</a>
            <button type="submit" class="btn btn-success book_btn ml-5" data-bus="1">Continue</button>
    </div>
    </form>
</fieldset>
<!-- END PERSONAL INFO -->

Views/Ticket_Reservation/Index.cshtml
@model IEnumerable<SRC_Travel_Agencies.Models.Upload_Bus>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/header_footer.cshtml";
}

<fieldset class="animated fadeIn">
    <form asp-controller="Ticket_Reservation" asp-action="Index" method="post">
        <div id="results">
            <!-- <h6>3 buses found</h6> -->
            <div class="row">
                <div class="col-md-12">
                    @foreach (var item in Model)
                    {
                            <div class="card">
                                <div class="card-body">
                                    <div class="row">
                                        <div class="col-md-3 bus-image">
                                            <img src="~/assets/images/p2.png" alt="bus" height="130" width="130">
                                                   <input type="hidden" value="@item.Bus_id" name="busId" class="Bus" />

                                                    </div>
                                        <div class="col-md-8 bus-details">
                                            <h5 class="card-title bus-name">Bus Name: <span>@Html.DisplayFor(modelItem => item.Bus_name)</span></h5>
                                            <div class="row card-text m-b-10 bus-description">
                                                <div class="col-sm-6 fs-14">
                                                    <i class="material-icons" style="font-size: 13px;">watch</i> @Html.DisplayNameFor(model => model.Category) <span> @Html.DisplayFor(modelItem => item.Category.Category_Name)</span>
                                                </div>
                                                <div class="col-sm-6 fs-14">
                                                    <i class="fa fa-road"></i> Ticket Per KM
                                                    <span class="p-r-5 fr"><span class="from">@Html.DisplayFor(modelItem => item.Bus_price)</span> </span>
                                                </div>
                                                <div class="col-sm-6 fs-14">
                                                    <i class="material-icons" style="font-size: 13px;">event_seat</i> Air Condition
                                                    <span class="p-r-5 fr"><span class="seats-left">@Html.DisplayFor(modelItem => item.Air_Condition)</span></span>
                                                </div>
                                            </div>
                                            <div class="p-t-13">
                                                                        <button type="submit" asp-route-id="@item.Bus_id"  class="btn btn-circle btn-success book_btn" data-bus="1">Select Destination</button>
                                                <div class="gallery1" style="display: none;">
                                                    <a href="assets/gallery/majaoni1.jpg">
                                                        <img src="assets/gallery/majaoni1.jpg" alt="" title="Majaoni Secondary Bus" />
                                                    </a>
                                                    <a href="assets/gallery/majaoni2.jpg">
                                                        <img src="assets/gallery/majaoni2.jpg" alt="" title="Majaoni Secondary Bus" />
                                                    </a>
                                                    <a href="assets/gallery/majaoni3.jpg">
                                                        <img src="assets/gallery/majaoni3.jpg" alt="" title="Majaoni Secondary Bus" />
                                                    </a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                    }
                </div>
            </div>
        </div>
    </form>
</fieldset>

Views/Ticket_Reservation/Ticket.cshtml
@model IEnumerable<SRC_Travel_Agencies.Models.Ticket>

@{
    ViewData["Title"] = "Ticket";
    Layout = "~/Views/Shared/header_footer.cshtml";
}
<fieldset class="animated fadeIn p-info">
    <main class="col-md-12">
        <div class="col-md-11 col-lg-9 col-xl-10 mx-auto window">
            <div class="ticket-container">
                @foreach (var item in Model)
                {
                    <div class="ticket">
                        <div class="ticket-header text-center">
                            <img src="~/admin_assets/img/logo_dark.png" alt="Logo" height="70" width="160">
                            <h4>Travel Ticket</h4>
                        </div>
                        <div class="ticket-body">
                            <div class="row">
                                <div class="col-6">
                                    <strong>From:</strong> @Html.DisplayFor(modelItem => item.From)<br>
                                    <strong>To:</strong> @Html.DisplayFor(modelItem => item.To)<br>
                                    <strong>Date:</strong> @Html.DisplayFor(modelItem => item.Date)<br>
                                    <strong>Seat Number:</strong> @Html.DisplayFor(modelItem => item.Seat_Number)
                                </div>
                                <div class="col-6">
                                    <strong>Distance:</strong> @Html.DisplayFor(modelItem => item.Distance)<br>
                                    <strong>Estimated Hours:</strong> @Html.DisplayFor(modelItem => item.Estimated_Hours)<br>
                                    <strong>Price:</strong> @Html.DisplayFor(modelItem => item.Ticket_Price)<br>
                                    <strong>Ticket ID:</strong> @Html.DisplayFor(modelItem => item.TicketId)
                                </div>
                            </div>
                        </div>
                        <div class="ticket-footer">
                            <div class="row">
                                <div class="col-6">
                                    <strong>Name:</strong> @Html.DisplayFor(modelItem => item.Name)
                                </div>
                                <div class="col-6">
                                    <strong>Email:</strong> @Html.DisplayFor(modelItem => item.Email)<br>
                                    <strong>Phone:</strong> @Html.DisplayFor(modelItem => item.Phone)
                                </div>
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </main>
    <div class="row justify-content-center buttons">
        <button type="button" class="btn btn-success" onclick="printContent()">Print Ticket</button>
        <a href="@Url.Action("Index", "Ticket_Reservation")" class="btn btn-success ml-5">Continue Booking</a>
    </div>
</fieldset>

<script>
    function printContent() {
        var ticketContent = document.querySelector('.ticket-container').outerHTML;

        var originalContent = document.body.innerHTML;
        document.body.innerHTML = ticketContent;

        window.print();

        document.body.innerHTML = originalContent;
        location.reload();
    }
</script>

<style>
    .ticket-container {
        margin-top: 20px;
    }

    .ticket {
        border: 2px solid #28a745;
        border-radius: 10px;
        padding: 15px;
        margin-bottom: 20px;
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
        background-color: #fff;
    }

    .ticket-header {
        margin-bottom: 15px;
    }

    .ticket-header h4 {
        margin-top: 10px;
        color: #28a745;
    }

    .ticket-body,
    .ticket-footer {
        padding: 10px 0;
    }

    .ticket-body .col-6,
    .ticket-footer .col-6 {
        margin-bottom: 10px;
    }

    .ticket-body strong,
    .ticket-footer strong {
        color: #333;
    }

    .buttons {
        margin-top: 20px;
    }

     
</style>

Views/Ticket_Reservation/UpdatePass.cshtml
@model SRC_Travel_Agencies.Models.Employees

@{
    ViewData["Title"] = "UpdatePass";
    Layout = "~/Views/Shared/header_no_nav.cshtml"; // Adjust the layout path according to your project structure
}

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <form asp-action="UpdatePass" method="post" class="needs-validation" novalidate>
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="Password" class="control-label"><h5>Update Password:</h5></label>
                    <input asp-for="Password" class="form-control" required/>
                    <div class="invalid-feedback"><h5 style="font-size: 15px;">Please provide a valid password.</h5></div>
                </div>
                <div class="form-group">
                    <button type="submit" class="btn btn-success">Update Password</button>
                </div>
            </form>
        </div>
    </div>
</div>

        <script>
            // Example of adding custom validation
            (function () {
                'use strict';
                window.addEventListener('load', function () {
                    var forms = document.getElementsByClassName('needs-validation');
                    var validation = Array.prototype.filter.call(forms, function (form) {
                        form.addEventListener('submit', function (event) {
                            if (form.checkValidity() === false) {
                                event.preventDefault();
                                event.stopPropagation();
                            }
                            form.classList.add('was-validated');
                        }, false);
                    });
                }, false);
            })();
        </script>